trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage:
  jobs:
  - job: InstallJob
    steps:
    - task: UseDotNet@2
      inputs:
        version: '5.0.x'
        includePreviewVersion: True

    - task: UseDotNet@2
      inputs:
        version: '3.0.x'
        includePreviewVersion: True
    
- template: stages/build.yml
- template: stages/deploy.yml
