trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
- stage:
  jobs:
  - job: InstallJob
    steps:
    - task: UseDotNet@2
      inputs:
        version: '2.2.0'
        includePreviewVersion: True

      
- template: stages/build.yml
- template: stages/deploy.yml
